no.nav.security.jwt.issuer.maskinporten:
  discoveryurl: https://ver2.maskinporten.no/.well-known/oauth-authorization-server
  validation.optional_claims: sub,nbf,aud
logging.level.no.nav.security: DEBUG